
BLENDER="C:\Program Files\Blender Foundation\Blender 3.2\blender.exe"
DIST=../dist

all : \
    $(DIST)/npcs.pnct \
    $(DIST)/npcs.scene \

$(DIST)/hexapod.scene : hexapod.blend export-scene.py
    $(BLENDER) --background --python export-scene.py -- "npcs.blend:Main" "$(DIST)/npcs.scene"

$(DIST)/hexapod.pnct : hexapod.blend export-meshes.py
    $(BLENDER) --background --python export-meshes.py -- "npcs.blend:Main" "$(DIST)/npcs.pnct" 
