
BLENDER="C:\Program Files\Blender Foundation\Blender 3.2\blender.exe"
DIST=../dist

all : \
    $(DIST)/npcs.pnct \
    $(DIST)/npcs.scene \

$(DIST)/npcs.scene : npcs_single.blend export-scene.py
    $(BLENDER) --background --python export-scene.py -- "npcs_single.blend:Main" "$(DIST)/npcs.scene"

$(DIST)/npcs.pnct : npcs_single.blend export-meshes.py
    $(BLENDER) --background --python export-meshes.py -- "npcs_single.blend:Main" "$(DIST)/npcs.pnct" 
